### ISSUE TITLE
function or associated item not found in `<T as template::Trait>::SubmitTransaction`

### ISSUE THREAD

**Issue by jingleizhang** [tomusdrw/sub0-offchain-workshop#3]
let result = T::SubmitTransaction::submit_signed(call);

function or associated item not found in `<T as template::Trait>::SubmitTransaction`

In the latest substrate version how can I solve this error? 

thanks

**Comment by tomusdrw** [comment]
Most likely this line is missing in your code: https://github.com/tomusdrw/sub0-offchain-workshop/blob/master/bin/node-template/runtime/src/template.rs#L36
